---
- hosts: "presto_coordinator_node"

  tasks:
    - name: "copy presto coordinator catalog"
      import_role:
        name: "install-presto-coordinator"
        tasks_from: "copy-presto-catalog.yml" 
      tags: ["copy-presto-catalog"]
      
- hosts: "presto_worker_node"

  tasks:
    - name: "copy presto worker catalog"
      import_role:
        name: "install-presto-worker"
        tasks_from: "copy-presto-catalog.yml" 
      tags: ["copy-presto-catalog"]
